include: 'https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml'

stages:
  - check
  - test

variables:
  BUNDLE: "de.haeckerfelix.AudioSharing.Devel.flatpak"
  MANIFEST_PATH: "build-aux/de.haeckerfelix.AudioSharing.Devel.json"
  FLATPAK_MODULE: "audio-sharing"
  APP_ID: "de.haeckerfelix.AudioSharing.Devel"
  RUNTIME_REPO: "https://nightly.gnome.org/gnome-nightly.flatpakrepo"
  CI_IMAGE_X86_64: "quay.io/gnome_infrastructure/gnome-runtime-images:gnome-master"

flatpak@x86_64:
  extends: ".flatpak@x86_64"

flatpak@aarch64:
  extends: ".flatpak@aarch64"

# Configure and run code checks
# Exits and fails if an error is encountered
checks:
  image: "rustlang/rust:nightly-slim"
  stage: check
  script:
    - apt update && apt install --no-install-recommends perl perl-modules-5.32 make -y
    - build-aux/checks.sh --verbose --force-install

# Lint the code
cargo-clippy:
  image: '${CI_IMAGE_X86_64}'
  stage: check
  tags:
    - flatpak
  script:
    - flatpak-builder --keep-build-dirs --user --disable-rofiles-fuse --stop-at=${FLATPAK_MODULE} flatpak_app --repo=repo ${BRANCH:+--default-branch=$BRANCH} ${MANIFEST_PATH}
    - echo "cargo clippy -- -D warnings" | flatpak-builder --disable-rofiles-fuse --build-shell=${FLATPAK_MODULE} flatpak_app ${MANIFEST_PATH}
