[package]
name = "audio-sharing"
version = "0.0.0"
authors = ["Felix Häcker <haeckerfelix@gnome.org>"]
edition = "2021"
license = "GPL-3.0-or-later"

[dependencies]
log = "0.4"
pretty_env_logger = "0.5"
regex = "1.10"
gettext-rs = { version = "0.7", features = ["gettext-system"] }
once_cell = "1.19"
adw = { version = "0.6", package = "libadwaita", features = ["v1_5"] }
gstreamer = "0.22"
gstreamer-rtsp-server = "0.22"
gtk = { version = "0.8", package = "gtk4", features = ["v4_10"] }
qrcode = "0.14"
pnet = "0.34"
